Apple branch
ChristianOtieno/apple-home-page-clone pull request #1
Opened 2019-10-04 22:01 UTC by ChristianOtieno

I have finished building the apple.com clone website. I am welcoming a review of my code, thanks.

2019-10-05 02:23 UTC, bolah2009 requested changes
## Awesome work @ChristianOtieno 

### [The clone](https://rawcdn.githack.com/ChristianOtieno/apple-home-page-clone/a943ddbe7a6004c488367b64fe8e83d93204bbbd/index.html) shows good use of CSS Backgrounds and Gradients. :100: 

A few required changes: Note that for this project, we have to make sure nothing is messed up. Please see difference in the source page and the clone below: 

| [Current clone](https://rawcdn.githack.com/ChristianOtieno/apple-home-page-clone/a943ddbe7a6004c488367b64fe8e83d93204bbbd/index.html) | [Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/) |
|:-----:|:-----:|
| ![image](https://user-images.githubusercontent.com/36057474/66248440-ff505280-e71e-11e9-9ce6-a8829a624dd7.png)  | ![image](https://user-images.githubusercontent.com/36057474/63733852-eb891500-c871-11e9-9989-2de9092b3fc5.png)|




#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-10-05 02:23 UTC, bolah2009 commented on stylelint.config.js
> +        "no-missing-end-of-source-newline": true,
Is there a reason you changing this config setting? :thinking:

2019-10-07 04:51 UTC, whiz25 commented on index.html
> +                        <a href="#" id="bottom-title">Watch the “Your Verse” film and explore the stories</a>
The text on lines 35 and 36 are overlapping. please correct that.

2019-10-07 04:55 UTC, whiz25 requested changes
## Awesome :+1: @ChristianOtieno 
You have made some suggested changes but you have forgotten to make your clone look like the original site. Look at my suggestions below;
- [x] see my comment
- [x] give your page a width of 100%. The background image and the four links below should cover the entire width of the page.

Please make those changes and re-submit for another review.

2019-10-07 17:19 UTC, whiz25 approved these changes
## Awesome :clap: 
You have implemented the suggested requirements. That's good.
Please go ahead and merge. Use ```Martin Afani``` when filling the form.

2019-10-07 17:57 UTC, merged